# Generated by Django 4.2.4 on 2023-10-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="type",
            field=models.CharField(
                choices=[("EPIC", "Epic"), ("TASK", "Task"), ("BUG", "Bug")], default="TASK", max_length=10
            ),
        ),
    ]
