# Generated by Django 4.2.6 on 2023-11-26 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_options"),
        ("boards", "0002_alter_board_creator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="issues", to="boards.board"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="category",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="categories",
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="created_issues", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
