app = "drosbros-kanban"
primary_region = "waw"

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = false
auto_start_machines = true

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256

[[statics]]
guest_path = "/code/static"
url_prefix = "/static/"
