# Pull official base image 
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get install -y gcc python3-dev musl-dev libmagic1 libffi-dev netcat-traditional \
    build-essential libpq-dev

COPY ./poetry.lock ./pyproject.toml /app/

RUN pip3 install poetry
RUN poetry config virtualenvs.in-project false
RUN poetry config virtualenvs.create false
RUN poetry install

COPY ./deployment/entrypoint.sh /entrypoint.sh

RUN chmod +x '/entrypoint.sh' && sed -i 's/\r$//g' '/entrypoint.sh'

COPY . /app/

ENTRYPOINT ["/entrypoint.sh"]

